import os

path = r"c:\Dev\Web-Landings\Macailabs.com\app\app\portfolio\page.tsx"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Verification
print(f"Line 24 (Index 23): {lines[23].strip()}")
print(f"Line 373 (Index 372): {lines[372].strip()}")

if "const portfolioItems" not in lines[23]:
    print("Error: Start line mismatch")
    exit(1)

# Note: The end line check is loose because comments might shift things if I was wrong about line counts,
# but view_file gave specific line numbers so we trust them.
# View_file said Line 373 is "]"
if "]" not in lines[372]:
    print("Error: End line mismatch")
    exit(1)

new_block = r"""const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    title: "Custom Linktree Website with AI Agent",
    description: "Custom website being the custom Linktree alternative with AI Chatbot. Created in Next.js.",
    type: "image",
    imageUrl: "/images/link-macai-dev.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents"],
    externalUrl: "https://link.macai.dev",
  },
  {
    id: 2,
    title: "AI Agents Directory",
    description: "A specialized directory I developed featuring a custom embedded AI Recommendation Agent.",
    type: "image",
    imageUrl: "/images/ainsiderstorenew.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "personal", "ai agents", "featured"],
    githubUrl: "https://github.com/piotrmacai/react-ainsiderstore-app",
    externalUrl: "https://ainsider.cloud",
  },
  {
    id: 3,
    title: "Video Portfolio Website",
    description: "High-performance Next.js website to showcase high-fidelity video content with seamless transitions.",
    type: "video",
    videoType: "vimeo",
    videoId: "1133675483",
    aspectRatio: "16:9",
    tags: ["all", "web", "visuals", "apps", "featured"],
    techStack: ["Next.js", "Framer Motion", "Vimeo SDK"],
    externalUrl: "https://creative.macai.dev",
  },
  {
    id: 4,
    title: "Promptr Gallery - AI Art Prompts Directory",
    description: "An interactive gallery of AI art prompts with a unique feature to customize and refine them for your own creative projects.",
    imageUrl: "/images/promptgallery.png",
    type: "image",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "automation", "featured"],
    externalUrl: "https://gallery.macai.dev",
  },
  {
    id: 5,
    title: "n8n automations",
    description: "Complete n8n AI and automation system for business",
    type: "image",
    imageUrl: "/images/ainsiderstore.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "personal", "automation", "featured"],
    externalUrl: "https://github.com/piotrmacai/n8n",
  },
  {
    id: 6,
    title: "Web and Automation Studio",
    description: "Website with complete serivces for Web and Automation Studio",
    type: "image",
    imageUrl: "/images/studiodev.png",
    aspectRatio: "16:9",
    tags: ["all", "ai agents", "web"],
    githubUrl: "https://github.com/piotrmacai/nextjs-personal-portfolio-app",
    externalUrl: "https://studio.macai.dev",
  },
  {
    id: 7,
    title: "Fullstack Chatbot App with OpenWebUI",
    description: "working with any n8n workflow",
    type: "image",
    imageUrl: "/images/customchatbot.png",
    aspectRatio: "16:9",
    tags: ["all", "featured", "web", "ai agents", "automation"],
    externalUrl: "https://github.com/piotrmacai/openwebui-n8n-app",
  },
  {
    id: 9,
    title: "Personal Telegram AI Agent",
    description: "Your Clawdbot/Moltot - Personal Telegram AI Agent with infinite memory working with n8n as backend",
    type: "image",
    imageUrl: "/images/telegramagent.png",
    aspectRatio: "16:9",
    tags: ["all", "ai agents", "featured", "automation"],
    externalUrl: "https://github.com/piotrmacai/openwebui-n8n-app",
  },
  {
    id: 10,
    title: "Fullstack Chatbot App with n8n agents",
    description: "allowing you to connect own n8n workflows - vibe-coded with Lovable, using Supabase for auth and database",
    type: "image",
    imageUrl: "/images/omnibot.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "automation", "featured"],
    externalUrl: "https://omnichat.macai.dev/",
  },
  {
    id: 11,
    title: "See My Github",
    description: "My Github profile with my projects - apps, websites, agents and automations",
    type: "image",
    imageUrl: "/images/git.jpg",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "featured"],
    techStack: ["n8n", "PostgreSQL", "React", "Docker"],
    githubUrl: "https://github.com/piotrmacai",
  },
  {
    id: 12,
    title: "Machtrans.pl Website",
    description: "Top SEO and ultra-fast Website in React.js for Transport Company",
    type: "image",
    imageUrl: "/images/machtrans.png",
    aspectRatio: "16:9",
    tags: ["all", "web"],
    externalUrl: "https://machtrans.pl",
  },
  {
    id: 13,
    title: "My Designs and Visuals",
    description: "My Github profile with my projects - apps, websites, agents and automations",
    type: "image",
    imageUrl: "/images/design.jpg",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "featured"],
    techStack: ["n8n", "PostgreSQL", "React", "Docker"],
    githubUrl: "https://www.behance.net/macaistudio",
  },
  {
    id: 14,
    title: "Chatbot app for n8n agents",
    description: "I architected a custom chatbot interface that integrates with any n8n workflow for complex business automations.",
    type: "image",
    imageUrl: "/images/n8n-workflows.webp",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "automation"],
    techStack: ["n8n", "PostgreSQL", "React", "Docker"],
    githubUrl: "https://github.com/piotrmacai/gemini-chatbot-app-v2",
  },
  {
    id: 15,
    title: "AI Product Designer",
    description: "I engineered a Gemini-powered application for generating and editing stunning product photos using advanced masking and AI infilling.",
    type: "image",
    imageUrl: "/images/AiProductDesigner.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "visuals", "apps", "ai agents"],
    techStack: ["Next.js", "Gemini AI", "Tailwind"],
    // externalUrl: "https://github.com/piotrmacai/Gemini-ProductPhotoStudio",
    githubUrl: "https://github.com/piotrmacai/Gemini-ProductPhotoStudio",
  },
  {
    id: 16,
    title: "Video Generation & Publishing Automation",
    description: "Complete AI system for generating marketing or ad video and publish it to social media",
    type: "image",
    imageUrl: "/images/videoautomation.jpg",
    aspectRatio: "16:9",
    tags: ["all", "ai agents", "visuals"],
    githubUrl: "https://github.com/piotrmacai/n8n/tree/main/ai-video-automation",
  },
  {
    id: 17,
    title: "Pgr-elektroteam.pl Website",
    description: "Multilingual Ecommerce with Supplements created at Shopify",
    type: "video",
    videoType: "vimeo",
    videoId: "1085338795",
    aspectRatio: "16:9",
    tags: ["all", "web", "ecommerce"],
    externalUrl: "https://pgr-elektroteam.pl/",
  },
  {
    id: 18,
    title: "AI Virtual try-on app",
    description: "Built with the Nano Banana model, this app enables real-time image generation and iterative editing.",
    type: "image",
    imageUrl: "/images/creativeai.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "visuals", "apps"],
    techStack: ["React", "Nano Banana API", "Cloudflare"],
    githubUrl: "https://github.com/piotrmacai/Gemini-Chatbot-App",
  },
  {
    id: 19,
    title: "n8n frontend fullstack chatbot app",
    description: "A versatile frontend chat interface dedicated for multiple various n8n workflows.",
    type: "image",
    imageUrl: "/images/n8nfrontendapp.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "apps", "ai agents", "automation"],
    githubUrl: "https://github.com/piotrmacai/Gemini-OmniChatbotApp",
  },
  {
    id: 20,
    title: "AI Leads Genarator",
    description: "Powerful and easy to use lead generator powered by AI and Gemini Maps search",
    type: "image",
    imageUrl: "/images/leadgenapp.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "apps"],
    githubUrl: "https://github.com/piotrmacai/LeadGenerationApp_v1.0",
  },
  {
    id: 227,
    title: "Voice Agent Starter Kit",
    description: "Developed using Vercel AI SDK and ElevenLabs for building interactive voice-based AI applications.",
    type: "image",
    imageUrl: "/images/elevenvercel.png",
    aspectRatio: "16:9",
    tags: ["web", "ai", "apps", "agents"],
    techStack: ["Vercel AI SDK", "ElevenLabs", "TypeScript"],
    externalUrl: "https://v0.app/chat/eleven-labs-agents-starter-xuyVdQFxPAE?ref=L4O3TN",
  },
  {
    id: 21,
    title: "AI Voice Agent with Elevenlabs",
    description: "I built an AI Voice Agent trained on proprietary business data, designed for seamless website integration.",
    type: "image",
    imageUrl: "/images/voicebotmacai.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents"],
    externalUrl: "https://macai.dev/contact",
  },
  {
    id: 248,
    title: "Multi-LLM Chatbot App with n8n workflows",
    description: "A versatile chat interface supporting multiple Gemini models and complex n8n backend workflows.",
    type: "image",
    imageUrl: "/images/geminin8n.png",
    aspectRatio: "16:9",
    tags: ["web", "ai", "apps", "agents", "n8n"],
    githubUrl: "https://github.com/piotrmacai/Gemini-chatapp-n8n-app",
  },
  {
    id: 22,
    title: "Oskmachowski.pl Website",
    description: "High-performance business platform with perfect SEO optimization and a custom AI assistant built in.",
    type: "video",
    videoType: "vimeo",
    videoId: "1121933690",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents"],
    externalUrl: "https://oskmachowski.pl",
  },
  {
    id: 23,
    title: "360 Marketing Reports AI System",
    description: "complete solution do generate marketing reports with conversational AI Agent",
    type: "image",
    imageUrl: "/images/marketingreport.png",
    aspectRatio: "16:9",
    tags: ["all", "web", "ai agents", "automation"],
    externalUrl: "https://github.com/piotrmacai/n8n/tree/main/marketing-reports-system",
  },
  {
    id: 279,
    title: "Landing Page for Business CRM",
    description: "Ultra fast landing page created in React.js for modern SaaS platforms.",
    type: "video",
    videoType: "vimeo",
    videoId: "1121924337",
    aspectRatio: "16:9",
    tags: ["web", "apps"],
    externalUrl: "https://ai.studio/apps/drive/1gj3DyNXi5-9fgxTmBWZ_OH9cvNEqRVBR",
  },
  {
    id: 24,
    title: "Lanellya.de Ecommerce store",
    description: "Multilingual Ecommerce created at Shopify for high-end fashion.",
    type: "video",
    videoType: "vimeo",
    videoId: "1088477211",
    aspectRatio: "16:9",
    tags: ["all", "web", "ecommerce"],
    externalUrl: "https://lanellya.de",
  },
  {
    id: 25,
    title: "Wordpress Blog Posts Automation",
    description: "Complete n8n system to manage full WordPress blog automation, from generation to posting.",
    type: "image",
    imageUrl: "/images/n8n-wordpress.png",
    aspectRatio: "16:9",
    tags: ["all", "ai agents", "web", "automation"],
    githubUrl: "https://github.com/piotrmacai/n8n/tree/main/wordpress-full-blog-automation",
  },
  {
    id: 26,
    title: "Rekrut Spark HR Website",
    description: "Business platform for an HR agency featuring a custom CRM for applicant management.",
    type: "video",
    videoType: "vimeo",
    videoId: "1100387757",
    aspectRatio: "16:9",
    tags: ["all", "web"],
    externalUrl: "https://rekrutspark.com",
  },
  {
    id: 27,
    title: "Invoice Automation and Reminder system",
    description: "Complete n8n system to manage full invoice automation, from generation to posting.",
    type: "image",
    imageUrl: "/images/invoice-automation.png",
    aspectRatio: "16:9",
    tags: ["all", "automation"],
    githubUrl: "https://github.com/piotrmacai/n8n/tree/main/invoice-reminder-v2",
  },
  {
    id: 28,
    title: "Transport Documents Automation",
    description: "Complete n8n system to manage full transport documents automation for drivers, from generation database records to posting.",
    type: "image",
    imageUrl: "/images/transport-automation.png",
    aspectRatio: "16:9",
    tags: ["all", "automation"],
    githubUrl: "https://github.com/piotrmacai/n8n/tree/main/transport-docs-automation",
  },
  {
    id: 29,
    title: "After-rave Ecommerce Store",
    description: "Multilingual Shopify-based ecommerce platform I developed for a specialized supplement brand.",
    type: "video",
    videoType: "vimeo",
    videoId: "1082919322",
    aspectRatio: "16:9",
    tags: ["all", "web", "ecommerce"],
    externalUrl: "https://after-rave.eu",
  },
  {
    id: 30,
    title: "SkinProject Clinic Website",
    description: "Full web presence for a premium beauty clinic and skincare brand.",
    type: "video",
    videoType: "vimeo",
    videoId: "1088475265",
    aspectRatio: "16:9",
    tags: ["all", "web"],
    externalUrl: "https://www.skinprojectclinic.pl/",
  },
  {
    id: 31,
    title: "Complete SEO & AEO Audit App",
    description: "complete solution for creating SEO & AEO audit reports for websites",
    type: "image",
    imageUrl: "/images/websiteseoaudit.png",
    aspectRatio: "16:9",
    tags: ["all", "ai agents", "web", "automation"],
    externalUrl: "https://github.com/piotrmacai/n8n/tree/main/seo-audit-v1",
  }
]"""

# Prepare new lines with newlines
replacement_lines = [line + "\n" for line in new_block.split('\n')]

# Replace
# Range is [23, 373) -> indices 23 to 372.
lines[23:373] = replacement_lines

with open(path, "w", encoding="utf-8") as f:
    f.writelines(lines)

print("Successfully written.")
